apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: emp-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments" , "pods"]
  verbs: ["get", "list"]
